version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - noctx

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
